### ISSUE TITLE
HA stops to sending commands after a few of commands

### ISSUE THREAD

**Issue by anti-fascista** [lievencoghe/cambridge_cxa#5]
Hi @lievencoghe !
Thanks for Your work. 
I successfully connect my cxa61. HA (docker on RPI) detects it by serial2net on 127.0.0.1 but after few commands stops to sending new commands randomly. If I turn off an on cxa61 HA detects correctly is changing os state and starts to sending a few commands correctly then stops again. If I restart HA the issues is present again with the same issues.
Have You an idea to solve my issue?
Thanks

**Comment by lievencoghe** [comment]
Hi,

I have just updated the component, so it works with a direct serial connection. You can still have the USB to serial device on a separate device though. You'll need to follow the instructions in the readme of this repo. Please let me know how you get on.

Cheers!

**Comment by anti-fascista** [comment]
Hi,
I tried new version but HA give me a lots of error:

Logger: homeassistant.config
Source: custom_components/cambridge_cxa/media_player.py:11
Integration: cambridge_cxa ([documentation](https://github.com/lievencoghe/cambridge_cxa), [issues](https://github.com/lievencoghe/cambridge_cxa/issues))
First occurred: 23:20:15 (1 occurrences)
Last logged: 23:20:15
Platform error: media_player

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/homeassistant/config.py", line 923, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/lib/python3.10/site-packages/homeassistant/loader.py", line 728, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/lib/python3.10/site-packages/homeassistant/loader.py", line 745, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/cambridge_cxa/media_player.py", line 11, in <module>
    from serial import Serial
ImportError: cannot import name 'Serial' from 'serial' (/config/.local/lib/python3.10/site-packages/serial/__init__.py)

I'm trying direct serial and indirect by socat...

Thanks

**Comment by anti-fascista** [comment]
Hi @lievencoghe !

I've done a fresh installation on Raspberry pi4: Ubuntu server 22.04 and HA core on docker but I have still this error:

homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error media_player.cambridge_cxa - cannot import name 'Serial' from 'serial' (/usr/local/lib/python3.10/site-packages/serial/__init__.py)

which python3 output:

/usr/bin/python3

python3 -m site output:

sys.path = [
    '/home/pi',
    '/usr/lib/python310.zip',
    '/usr/lib/python3.10',
    '/usr/lib/python3.10/lib-dynload',
    '/usr/local/lib/python3.10/dist-packages',
    '/usr/lib/python3/dist-packages',

/usr/local/lib/python3.10/dist-packages is empty...

Can you help me about?
thanks

**Comment by anti-fascista** [comment]
Hi,
Now is ok. In ssh on HA docker container I have uninstalled pyserial and reinstalled from Github. It works like a charm on direct serial connection.
Thanks
